paths:
  /api/v1/services/create:
    post:
      tags:
        - Create Formation Service
      summary: Create a new formation service (course, seminar, diploma, workshop)
      description: Create a new formation service with the provided details
      operationId: createNewFormationService
      parameters:
         - in: formData
           name: image
           type: file
         - in: formData
           name: exhibitorPhoto
           type: file
         - in: formData
           name: supportedByPhoto
           type: file
      requestBody:
        required: true
        content:
           multipart/form-data:
            schema:
                $ref: '#/definitions/Formation'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/SuccessResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /api/v1/services/?skip={skip}&taking={taking}:
    get:
      tags:
        - Get formation services
      summary: Get a list of formation services using pagination
      parameters:
        - in: query
          name: skip
          schema:
            type: integer
          required: true
          description: Position to init the pagination
        - in: path
          name: taking
          schema:
            type: integer
          required: true
          description: Number of records to retrieve per page
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/SuccessResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /api/v1/services/{id}:
    patch:
      tags:
        - Update Formation Service
      summary: Update an existent formation service
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the formation service to update
        - in: formData
          name: image
          type: file
        - in: formData
          name: exhibitorPhoto
          type: file
        - in: formData
          name: supportedByPhoto
          type: file
      requestBody:
        content:
           multipart/form-data:
            schema:
                $ref: '#/definitions/FormationUpdate'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/SuccessResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
        - Deelte a Formation Service
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the formation service to update
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/SuccessResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  

definitions:
  Formation:
    type: object
    required:
      - type
      - name
      - generalInfo
      - syllabus
      - hours
      - exhibitorName
      - organizedBy
      - cost
      - discounts
      - inscriptionUrl
      - supportedByName
    properties:     
      "type":
        type: string
        description:
          Name of type of the formation service. Only can be "course","seminar","workshop" or diploma.
      name:
        type: string
        description:
          Name of the formation service
      generalInfo:
        type: string
        description:
          Description of the formation service
      syllabus:
        type: string
        description:
          List of topics in the formation service separated by ';'
      hours:
        type: number
        description:
          Hours of duration
      exhibitorName:
        type: string
        description:
          Name of the exhibitor
      organizedBy:
        type: string
        description:
          Organization who organizes
      supportedByName:
        type: string
        description:
          Who supports the course, seminar, workshop or diploma
      cost:
        type: number
        description:
          Monetary cost
      discounts:
        type: string
        description:
          Informative text about discounts
      inscriptionUrl:
        type: string
        description:
          URL to inscription form
  FormationUpdate:
    type: object
    properties:     
      "type":
        type: string
        description:
          Name of type of the formation service. Only can be "course","seminar","workshop" or diploma.
      name:
        type: string
        description:
          Name of the formation service
      generalInfo:
        type: string
        description:
          Description of the formation service
      syllabus:
        type: string
        description:
          List of topics in the formation service separated by ';'
      hours:
        type: number
        description:
          Hours of duration
      exhibitorName:
        type: string
        description:
          Name of the exhibitor
      organizedBy:
        type: string
        description:
          Organization who organizes
      supportedByName:
        type: string
        description:
          Who supports the course, seminar, workshop or diploma
      cost:
        type: number
        description:
          Monetary cost
      discounts:
        type: string
        description:
          Informative text about discounts
      inscriptionUrl:
        type: string
        description:
          URL to inscription form
  SuccessResponse:
    type: object
    properties:
      isSuccess:
        type: boolean
      message:
        type: string
  ErrorResponse:
    type: object
    properties:
      isSuccess:
        type: boolean
      message:
        type: string

